import pygame


def main():
    pygame.init()

    screen = pygame.display.set_mode((640, 480))

    running = True
    font = pygame.Font(None, 80)
    title_text = "Sweeptag"
    #title_size = font.size(title_text)
    title_rendered = font.render(title_text, False, (255, 255, 255), (0, 0, 0))

    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT or (
                event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE
            ):
                running = False

            else:
                print(f"EVENT: {event}")

        screen.fill((250, 150, 0))
        screen.blit(title_rendered, (20, 20))
        pygame.display.flip()

    pygame.quit()


if __name__ == "__main__":
    main()
